name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          set -euo pipefail
          IFS=$'\n\t'
          # Check the code
          cargo build --all --frozen
          cargo test --all --frozen

      - name: Build the Docker image
        run: docker build -t website .
