name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create RustConfig
        run: |
          set -euo pipefail
          IFS=$'\n\t'
          rust_config="VERSION="
          rust_config=$rust_config$(cat rust-toolchain)
          echo $rust_config > RustConfig
          
      - name: Test
        run: |
          set -euo pipefail
          IFS=$'\n\t'
          # Check the code
          cargo build --all --locked
          cargo test --all --locked

      - name: Build the Docker image
        run: docker build -t website .
