name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check nightly version used by the buildpack
        # Make sure buildpack is using the same toolchain
        run: ci/check-nightly-version.sh
        
      - name: Test
        run: |
          set -euo pipefail
          IFS=$'\n\t'
          # Check the code
          cargo build --all --locked
          cargo test --all --locked

      - name: Build the Docker image
        run: docker build -t website .
